version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/splatoon2chat'
    environment:
      - 'DATABASE_PASSWORD=mysq_splat2'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_HOST=trust
      MYSQL_ROOT_PASSWORD: mysq_splat2
      MYSQL_DATABASE: splatoon2chat
    volumes:
      - 'db-data:/var/run/mysqld/mysqld.sock'