version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/splatoon2chat'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: splatoon2chat_test
    ports:
      - "3306:3306"
    volumes:
      - 'db-data:/var/run/mysqld/mysqld.sock'