version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/splatoon2chat'
    environment:
      - 'DATABASE_PASSWORD=mysq_splat2'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: splatoon2chat_test
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - '3306:3306'
    volumes:
      - 'db-data:/var/run/mysqld/mysqld.sock'