version: 2.1
jobs:
  build:
    machine:
      image: default
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: make directory make file
          command: |
            sudo mkdir /var/run/mysqld
            sudo touch /var/run/mysqld/mysqld.sock
            sudo chmod 754 /var/run/mysqld/mysqld.sock
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up --build -d
      - run:
          name: setup:db & test 
          command: |
            set -rwx
            docker-compose exec --env 'RAILS_ENV=test' web rails db:create
            docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
            docker-compose exec --env 'RAILS_ENV=test' web rails test