version: 2.1
jobs:
  build:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Docker-compose Build"
          command: |
            set -x
            docker-compose up --build -d

  # test:
  #   steps:
  #     - run:
  #         name: "test"
  #         command: |
  #           docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  #           docker-compose exec --env 'RAILS_ENV=test' web raild db:migrate
  #           docker-compose exec --env 'RAILS_ENV=test' web test