version: 2.1
jobs:
  build:
    machine:
      image: default
    working_directory: ~/projects/my-app/splatoon2chat
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up --build -d

      - run:
          name: database setup
          command: sleep 10

      - run:
          name: docker-compose log
          command: docker-compose logs | grep mysql

      - run:
          name: setup:db create
          command: |
            docker-compose exec web rails db:create RAILS_ENV=test
            docker-compose exec web rails db:migrate RAILS_ENV=test
            docker-compose exec web rails test RAILS_ENV=test
