version: 2.1
jobs:
  build:
    machine:
      image: default
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up --build -d
      - run:
          name: make directory make file
          command: |
            set -x
            docker-compose exec --env 'RAILS_ENV=test' web sudo mkdir /var/run/mysqld
            docker-compose exec --env 'RAILS_ENV=test' web sudo touch /var/run/mysqld/mysqld.sock
            docker-compose exec --env 'RAILS_ENV=test' web sudo chmod 754 /var/run/mysqld/mysqld.sock
            docker-compose exec --env 'RAILS_ENV=test' web sudo chown -R mysql /var/run/mysqld
      - run:
          name: setup:db create
          command: |
            set -x
            docker-compose exec --env 'RAILS_ENV=test' web sudo service mysql restart
            docker-compose exec --env 'RAILS_ENV=test' web rails db:create
      - run:
          name: setup:db migrate
          command: |
            set -x
            docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
      - run:
          name: test 
          command: |
            set -x
            docker-compose exec --env 'RAILS_ENV=test' web rails test